### ISSUE TITLE
Not picking up physical switch message...

### ISSUE THREAD

**Issue by briancday** [BobRak/OpenHAB-cm11a#6]
Bob:

Situation
======
I have installed and am using the CM11a binding and am using with Openhab2.  It works for turning on/off from PaperUI, but I have issues with OpenHab2 losing track of the state of a switch when triggered from a physical switch.  When this happens I see something like the lines below in the log.  Any ideas for troubleshooting?

10:46:14.808 [WARN ] [.binding.cm11a.internal.X10Interface] - Unexpected data received from X10 interface: 5b
10:46:14.815 [WARN ] [.binding.cm11a.internal.X10Interface] - Unexpected data received from X10 interface: 93
10:46:14.822 [WARN ] [.binding.cm11a.internal.X10Interface] - Unexpected data received from X10 interface: ef

Background
=======
- Running on Ubuntu 16

Binding file
brian@openhab:/usr/share/openhab2/addons$ ls -al
total 576
drwxr-xr-x 2 openhab openhab   4096 May 23 17:17 .
drwxr-xr-x 5 openhab openhab   4096 Jan 13 22:09 ..
-rwxr-xr-x 1 openhab openhab  33056 Jan 19 10:29 org.openhab.binding.cm11a.jar

- Config files:

cm11a.things
Bridge cm11a:cm11a:MyCm11a  [ serialPort="/dev/ttyUSB0" ] {
    Thing switch SwitchC1 [ HouseUnitCode="C1" ]
    Thing switch SwitchC3 [ HouseUnitCode="C3" ]
    Thing switch SwitchC5 [ HouseUnitCode="C5" ]
    Thing switch SwitchC7 [ HouseUnitCode="C7" ]
    Thing switch SwitchC13 [ HouseUnitCode="C13" ]
    Thing switch SwitchC15 [ HouseUnitCode="C15" ]
    Thing switch SwitchB3 [ HouseUnitCode="B3" ]
    Thing switch SwitchE5 [ HouseUnitCode="E5" ]
}

cm11a.items
Switch SwitchC1  "Basement Stairs"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchC1:switchstatus" }
Switch SwitchE5  "Porch Lights"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchE5:switchstatus" }
Switch SwitchC3  "Basement Main"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchC3:switchstatus" }
Switch SwitchC5  "Basement Music"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchC5:switchstatus" }
Switch SwitchC7  "Basement Workout"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchC7:switchstatus" }
Switch SwitchC13  "Man Cave"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchC13:switchstatus" }
Switch SwitchC15  "Basement Wall"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchC15:switchstatus" }
Switch SwitchB3  "Main Stairs"   <light>  (someGroup)  { channel="cm11a:switch:MyCm11a:SwitchB3:switchstatus" }

**Comment by BobRak** [comment]
X-10 devices are only able to receive commands over the powerline but are not able to send any status information. Because they are read only they can not notify the cm11a that the switch has been changed.  Therefore this is expected behaviour for X-10 devices.  If you are going to use X-10 switches you have to live with this limitation.

The CM11a does take one step to help. It listens on the powerline and tells the binding if a command has been sent by a controller to change the status of a device and it then updates openHAB.

**Comment by briancday** [comment]
Thanks for the reply.  

 

I understand that Openhab cannot poll an X10 switch for it’s status.  But, if I turned on an X10 switch shouldn’t that show up as an openhab event because the CM11a would notify openhab?

 

I used to catch x10 switch events with heyu prior to using Openhab.

 

B

**Comment by BobRak** [comment]
I don't currently have an cm11a hooked up to device that can run heyu. But, it is my recollection that heyu doesn't see anything when you use the switch to control a light. But, if you use a keypad then heyu will see that because the keypad sends the command over the powerline. If you have a setup with heyu and see differently please let me know. Thanks.

**Comment by briancday** [comment]
Heyu can see X10 switch activity.  For example, I have a single switch at
the top of the basement stairs that triggers several other switches.  It
cannot poll a switch and ask its current state.

I'm trying to migrate everything to openhab2.




On Jun 20, 2017 6:10 PM, "BobRak" <notifications@github.com> wrote:

I don't currently have an cm11a hooked up to device that can run heyu. But,
it is my recollection that heyu doesn't see anything when you use the
switch to control a light. But, if you use a keypad then heyu will see that
because the keypad sends the command over the powerline. If you have a
setup with heyu and see differently please let me know. Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BobRak/OpenHAB-cm11a/issues/6#issuecomment-309917315>,
or mute the thread

**Comment by BobRak** [comment]
Brian:

In you last email you say " I have a single switch at the top of the basement stairs that **triggers** several other switches." What does triggered mean? Is it connected to the lights as a regular switch would be. Or, does it us RF to send commands to an X-10 controller. Or, is it like a keypad that sens X-10 signals over the house wiring.

Please verify that you don't also have heyu running at the same time. Only one device can actively listen on the serial port at a time. If heyu is running at the same time that is likely the issue.

My cm11a binding uses the same technique to listen on the power line to X-10 messages and convert them into openHAB status updates. So, what ever heyu sees my cm11a binding should see the same thing/

Bob
